FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей системы
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    libpq-dev \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpangoft2-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    shared-mime-info \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Копируем requirements
COPY ./backend/requirements.txt .

# Устанавливаем зависимости Python
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Копируем код приложения
COPY ./backend .

# Создаём папки для staticfiles и media
RUN mkdir -p /app/staticfiles /app/media

# Expose порт
EXPOSE 8000

# По умолчанию команду переопределит docker-compose
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
