# Generated by Django 5.1.1 on 2026-06-10 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активная"),
                            ("inactive", "Неактивная"),
                            ("archived", "Архивирована"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teams/%Y/%m/%d/",
                        verbose_name="аватар",
                    ),
                ),
                (
                    "total_hours",
                    models.FloatField(default=0, verbose_name="всего часов"),
                ),
                (
                    "total_volunteers",
                    models.IntegerField(default=0, verbose_name="всего волонтёров"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="лидер",
                    ),
                ),
            ],
            options={
                "verbose_name": "команда",
                "verbose_name_plural": "команды",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "slots_available",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="доступно мест",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(default=True, verbose_name="открыт набор"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_slots",
                        to="events.event",
                        verbose_name="событие",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_slots",
                        to="teams.team",
                        verbose_name="команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "набор волонтёров",
                "verbose_name_plural": "наборы волонтёров",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "Лидер"),
                            ("member", "Член"),
                            ("moderator", "Модератор"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="роль",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="присоединился"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="команда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "член команды",
                "verbose_name_plural": "члены команды",
                "ordering": ["-joined_at"],
                "unique_together": {("team", "user")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="teams.TeamMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="члены",
            ),
        ),
        migrations.CreateModel(
            name="TeamApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="сообщение")),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="подано"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="рассмотрено"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="заявитель",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_team_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="рассмотрено кем",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="teams.recruitmentslot",
                        verbose_name="набор",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка на участие",
                "verbose_name_plural": "заявки на участие",
                "ordering": ["-applied_at"],
                "unique_together": {("slot", "applicant")},
            },
        ),
    ]
