# Generated by Django 5.1.1 on 2026-06-19 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="max_members",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(2)],
                verbose_name="макс. участников",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="requirements",
            field=models.TextField(blank=True, default="", verbose_name="требования"),
        ),
    ]
