# Generated by Django 5.1.1 on 2026-06-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregator", "0006_hackathon_sources"),
        ("teams", "0002_team_max_members_team_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teamups",
                to="aggregator.listing",
                verbose_name="возможность",
            ),
        ),
    ]
