# Generated by Django 5.1.1 on 2026-06-10 14:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hours_contributed",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="часов внесено",
                    ),
                ),
                (
                    "funds_raised_or_equivalent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Сумма собранных средств или денежный эквивалент вклада",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="собрано средств (или эквивалент)",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата записи"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impact_records",
                        to="events.event",
                        verbose_name="событие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись воздействия",
                "verbose_name_plural": "записи воздействия",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-recorded_at"],
                        name="impact_impa_user_id_b93439_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="impact_impa_recorde_18c604_idx"
                    ),
                ],
            },
        ),
    ]
