# Generated by Django 5.1.1 on 2026-06-10 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        help_text="Процент соответствия интересам/навыкам пользователя (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="оценка соответствия",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="причина рекомендации"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="events.event",
                        verbose_name="событие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "рекомендация события",
                "verbose_name_plural": "рекомендации событий",
                "ordering": ["-match_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-match_score"],
                        name="recommendat_user_id_c2a798_idx",
                    )
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
