# Generated by Django 5.1.1 on 2026-06-12 13:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('source_type', models.CharField(choices=[('telegram', 'Telegram-канал'), ('vk', 'VK-паблик'), ('website', 'Сайт / API'), ('discord', 'Discord'), ('rss', 'RSS-фид'), ('manual', 'Ручной ввод')], max_length=20, verbose_name='тип источника')),
                ('identifier', models.CharField(help_text='Username Telegram-канала, screen_name паблика VK или URL/эндпоинт для сайта', max_length=255, verbose_name='идентификатор')),
                ('url', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('trust_level', models.CharField(choices=[('quarantine', 'Карантин (всё на модерацию)'), ('trusted', 'Доверенный (авто-публикация при высокой уверенности AI)')], default='quarantine', max_length=20, verbose_name='уровень доверия')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('poll_interval_minutes', models.PositiveIntegerField(default=120, verbose_name='интервал опроса (мин)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Специфичные для источника параметры (категории, лимиты и т.п.)', verbose_name='доп. настройки')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True, verbose_name='последний опрос')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='последний успешный сбор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'источник',
                'verbose_name_plural': 'источники',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_type', 'is_active'], name='aggregator__source__a96dfb_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='ID сообщения/поста в источнике', max_length=255, verbose_name='внешний ID')),
                ('source_url', models.URLField(blank=True, verbose_name='ссылка на оригинал')),
                ('raw_text', models.TextField(blank=True, verbose_name='текст')),
                ('raw_html', models.TextField(blank=True, verbose_name='HTML')),
                ('media_urls', models.JSONField(blank=True, default=list, verbose_name='медиа')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='хэш контента')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processed', 'Обработан'), ('duplicate', 'Дубликат'), ('skipped', 'Отфильтрован'), ('error', 'Ошибка')], default='new', max_length=20, verbose_name='статус')),
                ('error_message', models.TextField(blank=True, verbose_name='сообщение об ошибке')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='собрано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='обработано')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='aggregator.source', verbose_name='источник')),
            ],
            options={
                'verbose_name': 'сырой элемент',
                'verbose_name_plural': 'сырые элементы',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('listing_type', models.CharField(choices=[('volunteer', 'Волонтёрство'), ('hackathon', 'Хакатон'), ('olympiad', 'Олимпиада'), ('forum', 'Форум'), ('grant', 'Грант'), ('internship', 'Стажировка'), ('contest', 'Конкурс'), ('other', 'Другое')], default='other', max_length=20, verbose_name='тип')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='статус')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='организация')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='регион')),
                ('is_online', models.BooleanField(default=False, verbose_name='онлайн')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='дедлайн заявки')),
                ('source_url', models.URLField(blank=True, verbose_name='ссылка на источник')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='обложка')),
                ('ai_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='уверенность AI')),
                ('is_featured', models.BooleanField(default=False, verbose_name='рекомендуемое')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='дата модерации')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='заметки модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listings', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('raw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='aggregator.rawitem', verbose_name='сырой элемент')),
                ('tags', models.ManyToManyField(blank=True, related_name='listings', to='aggregator.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['status'], name='aggregator__status_f2a538_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['content_hash'], name='aggregator__content_6b2ce1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawitem',
            unique_together={('source', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'application_deadline'], name='aggregator__status_bad9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type'], name='aggregator__listing_3ab4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['region'], name='aggregator__region_63f9c6_idx'),
        ),
    ]
