# Generated by Django 5.1.1 on 2026-06-10 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("environment", "Окружающая среда"),
                            ("education", "Образование"),
                            ("social", "Социальная помощь"),
                            ("health", "Здравоохранение"),
                            ("culture", "Культура и искусство"),
                            ("sports", "Спорт и активный образ жизни"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("upcoming", "Предстоящее"),
                            ("ongoing", "В процессе"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="дата начала")),
                ("end_date", models.DateTimeField(verbose_name="дата окончания")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="место проведения"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="долгота",
                    ),
                ),
                (
                    "max_volunteers",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="максимум волонтёров",
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        blank=True,
                        help_text="Разделите запятыми",
                        verbose_name="требуемые навыки",
                    ),
                ),
                (
                    "volunteer_hours",
                    models.FloatField(
                        default=0,
                        help_text="Сколько часов получит каждый волонтёр",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="часы волонтёрства",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="контактное лицо"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="контактный телефон"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="контактный email"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/%Y/%m/%d/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="рекомендуемое"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="онлайн событие"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["organizer", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="организатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие",
                "verbose_name_plural": "события",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventVolunteer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Заявился"),
                            ("approved", "Одобрено"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "hours_completed",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="завершённые часы",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата заявки"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата присоединения"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата завершения"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="рейтинг",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="отзыв")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="событие",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="волонтёр",
                    ),
                ),
            ],
            options={
                "verbose_name": "участие волонтёра",
                "verbose_name_plural": "участия волонтёров",
                "ordering": ["-applied_at"],
                "unique_together": {("event", "volunteer")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="volunteers",
            field=models.ManyToManyField(
                blank=True,
                related_name="participated_events",
                through="events.EventVolunteer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="волонтёры",
            ),
        ),
        migrations.CreateModel(
            name="EventRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="events.event",
                        verbose_name="событие",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="волонтёр",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка события",
                "verbose_name_plural": "оценки событий",
                "unique_together": {("event", "volunteer")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_date"], name="events_even_status_dfba18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer"], name="events_even_organiz_266ef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["category"], name="events_even_categor_aca11d_idx"
            ),
        ),
    ]
