# Generated by Django 5.1.1 on 2026-06-10 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "icon",
                    models.CharField(
                        default="🏆",
                        help_text="Emoji или путь к изображению",
                        max_length=10,
                        verbose_name="иконка (emoji)",
                    ),
                ),
                ("icon_url", models.URLField(blank=True, verbose_name="URL иконки")),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Описание как получить это достижение",
                        max_length=100,
                        verbose_name="условие получения",
                    ),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("events_completed", "Завершено событий"),
                            ("hours_completed", "Часов отработано"),
                            ("teams_joined", "Команд присоединено"),
                        ],
                        default="events_completed",
                        max_length=30,
                        verbose_name="тип условия",
                    ),
                ),
                (
                    "criteria_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text='Например, 5 для "завершить 5 событий"',
                        verbose_name="значение условия",
                    ),
                ),
                ("points", models.IntegerField(default=10, verbose_name="баллы")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Обычное"),
                            ("uncommon", "Редкое"),
                            ("rare", "Очень редкое"),
                            ("legendary", "Легендарное"),
                        ],
                        default="common",
                        max_length=20,
                        verbose_name="редкость",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
            ],
            options={
                "verbose_name": "достижение",
                "verbose_name_plural": "достижения",
                "ordering": ["-points"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                (
                    "icon",
                    models.CharField(default="🌟", max_length=10, verbose_name="иконка"),
                ),
                ("min_points", models.IntegerField(verbose_name="минимум баллов")),
                (
                    "max_points",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="максимум баллов"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="HEX код цвета",
                        max_length=7,
                        verbose_name="цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "уровень",
                "verbose_name_plural": "уровни",
                "ordering": ["min_points"],
            },
        ),
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_hours",
                    models.FloatField(default=0, verbose_name="всего часов"),
                ),
                (
                    "total_events",
                    models.IntegerField(default=0, verbose_name="всего событий"),
                ),
                (
                    "total_teams",
                    models.IntegerField(default=0, verbose_name="всего команд"),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, verbose_name="всего баллов"),
                ),
                (
                    "best_month_hours",
                    models.FloatField(default=0, verbose_name="часов в лучший месяц"),
                ),
                (
                    "best_month",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="лучший месяц"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="achievements.level",
                        verbose_name="уровень",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "статистика",
                "verbose_name_plural": "статистики",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="получено"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.badge",
                        verbose_name="достижение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "достижение пользователя",
                "verbose_name_plural": "достижения пользователя",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
