# Generated by Django 5.1.1 on 2026-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of volunteering interest categories, e.g. ["education", "environment"]',
                verbose_name="interests",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of skills, e.g. ["first aid", "photography", "teaching"]',
                verbose_name="skills",
            ),
        ),
    ]
