# Generated by Django 5.1.1 on 2026-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_interests_customuser_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status_label",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="статус-бейдж"
            ),
        ),
    ]
