# Generated by Django 5.1.1 on 2026-06-14 06:29

from django.db import migrations, models


def set_default_status_label(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(status_label='').update(status_label='Гость')


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_status_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status_label",
            field=models.CharField(
                blank=True, default="Гость", max_length=50, verbose_name="статус-бейдж"
            ),
        ),
        migrations.RunPython(set_default_status_label, migrations.RunPython.noop),
    ]
